---
title: "CVA examples"
format: html
editor: visual
---

## 

## Motivating example

```{r}
library(MASS)
library(tidyverse)
```

```{r}
cov.mtx <- matrix(c(1,0.8,
                 0.8, 1), nrow = 2, ncol = 2)

g1 <- mvrnorm(200, c(0,-1.25), Sigma=cov.mtx)
g2 <- mvrnorm(200, c(0,1.25), Sigma=cov.mtx)

G1 <- tibble(X = g1[,1], Y = g1[,2], group="Group 1")
G2 <- tibble(X = g2[,1], Y = g2[,2], group="Group 2")

G <- bind_rows(G1,G2)


p1 <-
  ggplot(G, aes(x = X, y = Y, color=group)) + 
  geom_point(alpha=0.5) +
  coord_fixed() + 
  xlim(-4.5,4.5) + 
  ylim(-4.5,4.5) +
  theme(legend.position="none")

p1
ggsave("cva-motivating-example.pdf")

```



```{r}
G.pca <- prcomp(select(G, -group))
G.scores <- as_tibble(G.pca$x)

rot.DF <- as_tibble(G.pca$rotation)

pc1.xend <- rot.DF[[1,1]] * 2 * G.pca$sdev[1]
pc1.yend <- rot.DF[[2,1]] * 2 * G.pca$sdev[1]

pc2.xend <- rot.DF[[1,2]] * 2 * G.pca$sdev[2]
pc2.yend <- rot.DF[[2,2]] * 2 * G.pca$sdev[2]




p1 + 
  geom_segment(x = -pc1.xend, y = -pc1.yend, 
               xend = pc1.xend, yend = pc1.yend,
               color="black") 
  # geom_segment(x = -pc2.xend, y = -pc2.yend, 
  #              xend = pc2.xend, yend = pc2.yend,
  #              color="black") 


ggsave("cva-motivating-PCA.pdf")

```

```{r}
G.lda <- lda(group ~ ., data = G)
G.lda$scaling



rot.DF <- as_tibble(G.lda$scaling)

cva1.xend <- rot.DF[[1,1]] 
cva1.yend <- rot.DF[[2,1]] 




p1 + 
  geom_segment(x = -cva1.xend, y = -cva1.yend, 
               xend = cva1.xend, yend = cva1.yend,
               color="black") 



ggsave("cva-motivating-CVA.pdf")
```


```{r}
ggplot(G.scores, aes(x = PC1, y = PC2)) +
  geom_point() +
  coord_fixed()
```

```{r}

```


