---
title: "Bio 723, Assignment 06"
author: "Your Name and NetID here!"
format: 
  html:
    embed-resources: true
    fig_caption: true
---

# Instructions

Create a R Markdown document and answer the questions below using code blocks that generate the correct outputs. I encourage you to use explanatory text in your markdown document, however **each of your solutions should show how to generate the answer using R code**. I encourage you to write "robust" solutions wherever possible. A good rule of thumb for judging whether your solution is appropriately "robust" is to ask yourself "If I added additional observations or variables to this data set, or if the order of variables changed, would my code still compute the right solution?"

Make sure your R Markdown is nicely formatted -- use headers, bullets, numbering, etc so that the structure of the document is clear.

Make sure to "knit" you document before submission to confirm that all code blocks and formatting is as you expect.

When completed, title your R Markdown file as follows:

-   `netid-assignment_06-Spring2023.Rmd`

Submit both your Markdown file and the generated HTML document via the Assignments submission section on Sakai.

# Make your solutions computable

For each of the problem below (except in cases where you are asked to discuss your interpretaion) write R code blocks that will **compute appropriate solutions**. A good rule of thumb for judging whether your solution is appropriately "computable" is to ask yourself "If I added additional observations to this data set, would my code still compute the right solution?"


# Problems



1. For each of the data set listed below, do the following:

    * [`pollen`](https://raw.githubusercontent.com/Bio723-class/example-datasets/master/ABD-father-mutations.csv): Hybrid offspring from different species are often sterile. Moyle et al. (2004) studied hybrids in the plant species *Silene*, and quantified the proportion of pollen that is sterile as a function of genetic distance.  

    * [`mutations`](https://raw.githubusercontent.com/Bio723-class/example-datasets/master/ABD-father-mutations.csv): Fathers transmit more new mutations to their offspring that do mothers, due to the fact that copying errors occur during sperm production.  There is interst in how father's age affects the number of mutations.  Kong et al. (2012) use genome sequencing of 21 father-child pairs to quantify the number of new mutations inhereited from each father.  



    a. Fit the linear regression relating the response variable to the predictor variable 
  
    a. Draw a scatter plot showing the relationship between the predictor and response variable, superimposing the linear regression line on the plot 

    a. Draw a residual plot 
  
    a. Give the coefficients (slope and intercept) of the regression, in the form: $\hat{Y} = a + bX$. 

    a. How much of the variation in the response variable can be "explained" by variation in the explanatory variable? 

    a. Discuss whether you think the linear regression model is an appropriate way to model the relationship of interest.  Point to features of the data, your visualizations,  etc. to support your argument. 



1. Using _vector arithmetic operations_, write your own regression function (`vec.regression()`, in R. Your solutions should employ vector operations of the type we reviewed in lecture (dot product, vector addition, subtraction, etc). *Your answers should not employ built-in functions* like `mean()`, `var()`, `cov()`, etc but can include basic vector functions like `length()`, `sum()`, `sqrt()`, etc as well as all the basic arithmetic operators include the dot product operator `%.%`

    The function will take as it's input two vectors, $\vec{x}$ and $\vec{y}$. The function should return a list contining:

      a. The regression coefficients $a$ and $b$ in the regression equation $\vec{\widehat{\mathbf{y}}} = a + b\vec{\mathbf{x}}$
      a. The fitted (predicted) values of $Y$ for each observed value of $X$
      a. The residuals
      a. The coefficient of determination, $R^2$

1. Demonstrate your regression function by using it to carry out regressions of `Sepal.Length` on `Sepal.Width` separately for the `versicolor' and `virginica' specimens from the `iris` data set. Include |ggplot| created plots in which you use the `geom_point()` and `geom_abline()` functions to illustrate your calculated regression line. To test your function, compare your regression coefficients and coefficient of determination to the same values returned by the built in `lm()` function. 


